image: docker:19.03.8
services:
  - docker:19.03.8-dind

stages:
  - build
  - test
  - release

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_VERIFY: 1
  DOCKER_CERT_PATH: /certs/client

before_script:
  - if [ -n "$GROUP_CI_REGISTRY_USER" -a -n "$GROUP_CI_REGISTRY_PASSWORD" ]; then echo "Group CI login..."; docker login -u "$GROUP_CI_REGISTRY_USER" -p "$GROUP_CI_REGISTRY_PASSWORD" registry.gitlab.iitsp.com/allworldit/docker; fi
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"

build:
  stage: build
  script:
    - set
    - export CONTAINER_TEST_IMAGE="$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
    - docker build --pull --build-arg=VERSION_INFO="$CI_PROJECT_TITLE [$CI_PROJECT_PATH_SLUG] build $CI_BUILD_ID commit $CI_COMMIT_SHORT_SHA ($(date -Iseconds))" --tag "$CONTAINER_TEST_IMAGE" .
    # Branch tags are required for CI
    - docker push "$CONTAINER_TEST_IMAGE"

test:
  stage: test
  script:
    - export CONTAINER_TEST_IMAGE="$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
    - docker pull "$CONTAINER_TEST_IMAGE"
    - docker run -e CI=true "$CONTAINER_TEST_IMAGE"

# Releases are only done for the master repository, which maps to "latest"
release-image:
  stage: release
  script:
    - export CONTAINER_TEST_IMAGE="$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
    - export CONTAINER_DATED_IMAGE="$CI_REGISTRY_IMAGE:$(date +%Y%m%d)"
    - export CONTAINER_RELEASE_IMAGE="$CI_REGISTRY_IMAGE:latest"
    - docker pull "$CONTAINER_TEST_IMAGE"
    - docker tag "$CONTAINER_TEST_IMAGE" "$CONTAINER_DATED_IMAGE"
    - docker tag "$CONTAINER_TEST_IMAGE" "$CONTAINER_RELEASE_IMAGE"
    - docker push "$CONTAINER_DATED_IMAGE"
    - docker push "$CONTAINER_RELEASE_IMAGE"
  only:
    - master

