image: docker:19.03.8
services:
  - docker:19.03.8-dind

stages:
  - build
  - test
  - release

variables:
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_VERIFY: 1
  DOCKER_CERT_PATH: /certs/client
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest

before_script:
  - if [ -n "$GROUP_CI_REGISTRY_USER" -a -n "$GROUP_CI_REGISTRY_PASSWORD" ]; then echo "Group CI login..."; docker login -u "$GROUP_CI_REGISTRY_USER" -p "$GROUP_CI_REGISTRY_PASSWORD" registry.gitlab.iitsp.com/allworldit/docker; fi
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"

build:
  stage: build
  script:
    - docker build --pull -t "$CONTAINER_TEST_IMAGE" .
    # Only push the image if its not master
    - if [ "$CI_COMMIT_REF_NAME" != "master" ]; then docker push "$CONTAINER_TEST_IMAGE"; fi

test:
  stage: test
  script:
    - docker pull "$CONTAINER_TEST_IMAGE"
    - docker run -e CI=true "$CONTAINER_TEST_IMAGE"

# Releases are only done for the master repository, which maps to "latest"
release-image:
  stage: release
  script:
    - docker pull "$CONTAINER_TEST_IMAGE"
    - docker tag "$CONTAINER_TEST_IMAGE" "$CONTAINER_RELEASE_IMAGE"
    - docker push "$CONTAINER_RELEASE_IMAGE"
  only:
    - master

